sonar.projectKey=task-2
sonar.projectName=task-2

sonar.sources=.
sonar.sourceEncoding=UTF-8

# Python detection
sonar.inclusions=**/*.py

# Optional cleanup
sonar.exclusions=**/__pycache__/**,**/*.pyc
